defaults: &defaults
  host: "localhost"
  port: "6379"

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  user: "<%=ENV['OPENSHIFT_REDIS_HOST']%>"
  password: "<%=ENV['OPENSHIFT_REDIS_PORT']%>"
