defaults: &defaults
  user: "1"
  password: "2"

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  user: "<%=ENV['OPENSHIFT_RESQUE_USER']%>"
  password: "<%=ENV['OPENSHIFT_RESQUE_PASSWORD']%>"
